language: java
jdk:
  - oraclejdk9
  - openjdk8

matrix:
  include:
  - jdk: openjdk9
    before_install:
    - rm "${JAVA_HOME}/lib/security/cacerts"
    - ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"
    
after_success:
  - mvn clean test jacoco:report coveralls:report
