language: java

matrix:
  include:
  - jdk: openjdk9
    before_install:
    - rm "${JAVA_HOME}/lib/security/cacerts"
    - ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"
  - jdk: openjdk8

after_success:
  - mvn clean test jacoco:report coveralls:report
