name: Java CI

on: [push, pull_request]

jobs:
  build:
    
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        java: [1.8, 1.14]
        include: # define single matrix case that performs upload
        - os: ubuntu-latest
          java: 1.8
          upload: true

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Build with Maven
      run: mvn package assembly:single --file pom.xml
    - name: upload jar as asset
      if: matrix.upload && github.event_name == 'pull_request' && github.base_ref == 'master'
      uses: actions/upload-artifact@v2
      with:
        name: zipped-ripme-jar
        path: target/*dependencies.jar

# vim:set ts=2 sw=2 et:
